### ISSUE TITLE
Circular dependency detected while autoloading constant User (RuntimeError)

### ISSUE THREAD

**Issue by pupeno** [gonzalo-bulnes/simple_token_authentication#272]
If I add this line:

```ruby
acts_as_token_authentication_handler_for User
```

to my ApplicationController, I get the error: `load_missing_constant': Circular dependency detected while autoloading constant User (RuntimeError)

If I add it to another controller down the hierarchy, then it works fine.

This is the full backtrace:

```text
/Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:492:in `load_missing_constant': Circular dependency detected while autoloading constant User (RuntimeError)
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/pupeno/Documents/code/calltobuzz/app/admin/user.rb:3:in `<top (required)>'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:526:in `load_missing_constant'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/pupeno/Documents/code/calltobuzz/app/controllers/application_controller.rb:13:in `<class:ApplicationController>'
	from /Users/pupeno/Documents/code/calltobuzz/app/controllers/application_controller.rb:3:in `<top (required)>'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/inherited_resources-1.6.0/app/controllers/inherited_resources/base.rb:11:in `<module:InheritedResources>'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/inherited_resources-1.6.0/app/controllers/inherited_resources/base.rb:1:in `<top (required)>'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activeadmin-1.0.0.pre4/lib/active_admin/base_controller/authorization.rb:2:in `<module:ActiveAdmin>'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activeadmin-1.0.0.pre4/lib/active_admin/base_controller/authorization.rb:1:in `<top (required)>'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activeadmin-1.0.0.pre4/lib/active_admin/base_controller.rb:1:in `<top (required)>'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:248:in `controllers_for_filters'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:241:in `block (2 levels) in <class:Application>'
	from /Users/pupeno/Documents/code/calltobuzz/config/initializers/active_admin.rb:276:in `block in <top (required)>'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activeadmin-1.0.0.pre4/lib/active_admin.rb:71:in `setup'
	from /Users/pupeno/Documents/code/calltobuzz/config/initializers/active_admin.rb:3:in `<top (required)>'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/pupeno/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/pupeno/.rvm/gems/ruby-2.3.1@calltobuzz/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/pupeno/Documents/code/calltobuzz/config/environment.rb:7:in `<top (required)>'
	from /Users/pupeno/Documents/code/calltobuzz/test/test_helper.rb:9:in `require'
	from /Users/pupeno/Documents/code/calltobuzz/test/test_helper.rb:9:in `<top (required)>'
	from /Users/pupeno/Documents/code/calltobuzz/test/integration/email_notification.rb:3:in `require'
	from /Users/pupeno/Documents/code/calltobuzz/test/integration/email_notification.rb:3:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

I'm not sure what other information from my project can be of help here. I'm happy to investigate for you.

A simple workaround would be for acts_as_token_authentication_handler_for to accept the class name as a string or proc to be evaluated later.

**Comment by gonzalo-bulnes** [comment]
Hello @pupeno, interesting problem! A few questions:

1.
What is being required in `app/models/admin/user.rb` line 3? (I'd like to understand why this is happening in your context before working around the issue.)

2.
Is this happening in your test environment? (Just trying to confirm if I am reading the stack trace properly.) If it is, can you confirm if it also happens in your development environment? (I expect it does, but would like to discard any loading issue related to the `test/test_helper.rb`.)

Also, the first few lines of your model and controller can probably be helpful, just for me to get a better idea of the context : )

**Comment by pupeno** [comment]
This is the whole admin/user.rb file, it's ActiveAdmin, which may be the issue:

```ruby
# Copyright 2016 José Pablo Fernández Silva

ActiveAdmin.register User do
  index do
    selectable_column
    id_column
    column :email
    column :current_sign_in_at
    column :sign_in_count
    column :created_at
    actions
  end

  filter :id, as: :string, filters: %w{equals}
  filter :email
  filter :unconfirmed_email
  filter :name
  filter :preferred_name
  filter :aggreed_to_terms_at
  filter :reset_password_sent_at
  filter :current_sing_in_at
  filter :last_sing_in_at
  filter :confirmed_at
  filter :confirmation_sent_at
  filter :failed_attempts
  filter :lockd_at
end
```

It happens in the development environment.

models/user.rb starts like this:

```ruby
# Copyright 2016 José Pablo Fernández Silva

class User < ActiveRecord::Base
  has_many :memberships, inverse_of: :user
  has_many :organizations, through: :memberships
  has_many :social_media_accesses
  has_many :task_statuses

  validates :agree_to_terms, acceptance: {accept: true}, unless: :skip_sign_up_validations

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable # Include default devise modules. Others available are: :timeoutable and :omniauthable
  acts_as_token_authenticatable
  attr_accessor :skip_sign_up_validations
  accepts_nested_attributes_for :memberships
  has_paper_trail
  audit_validation_errors
  before_validation :set_preferred_name
```

**Comment by gonzalo-bulnes** [comment]
Only your `User` is _token authenticatable_...

> [If I enable _token authentication handling_] to my `ApplicationController`, I get the error: `load_missing_constant': Circular dependency detected while autoloading constant User (RuntimeError). If I add it to another controller down the hierarchy, then it works fine.

I wonder if your `ApplicationController` somehow already attempts to load `Admin::User` and if `User` could be ambiguous in the `ApplicationController` context. (I'm thinking aloud...)

1.
Does replacing `User` by `::User` in your `ApplicationController` still trigger the error?

```ruby
# app/controllers/application_controller.rb

# ...

# User might mean Admin::User in some controllers, ::User is unambiguous
acts_as_token_authentication_handler_for ::User
```

2.
If the error stops happening, I would expect you have some controllers defined inside of the `Admin` namespace (you may have created some or maybe ActiveAdmin does define some). And I would expect to be able to reproduce the error by enabling token authentication handling the way you did in any admin controller:

```ruby
# app/controllers/admin/some_controller.rb

# ...

# Unless I'm wrong, this should trigger the circular dependency error:
acts_as_token_authentication_handler_for User
```

If this is correct, then the issue is just caused by the sum of constants lookup in Ruby (which causes `User` to eventually mean different things in different namespaces) and autoloading (which causes the files to be required the first time the constants they define appear). It would really be an issue, neither in your code, ActiveAdmin or Simple Token Authentication just something to be aware of.

I may be wrong, however, can you confirm please? : )

**Comment by gonzalo-bulnes** [comment]
Hi @pupeno, any news on this?

**Comment by pupeno** [comment]
I'm sorry, I've been supper busy. I'll have some answer during this weekend.

**Comment by gonzalo-bulnes** [comment]
@pupeno No worries! And no pressure, I was just wondering : )

**Comment by pupeno** [comment]
1.
```ruby
  acts_as_token_authentication_handler_for ::User
```
generates the same error.

2.

Yes, active admin generates controllers that inherit from ApplicationController... or is it ActionController::Base? I'm not entirely sure, but adding 

```ruby
acts_as_token_authentication_handler_for User
```

did not change anything there. I added it to all my admin controllers.

**Comment by leonardoprg** [comment]
Hello guys,

same erro here, any suggestion to fix?
